# Generated by Django 5.2.8 on 2025-12-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('categoriaUsuario', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField()),
                ('desc_evento', models.CharField(max_length=100)),
                ('desc_area', models.CharField(max_length=100)),
                ('desc_leitor', models.CharField(max_length=100)),
                ('ent_sai', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='meuapp.usuario', to_field='matricula')),
            ],
            options={
                'unique_together': {('usuario', 'data_acesso', 'desc_evento', 'desc_area', 'ent_sai')},
            },
        ),
    ]
