# Generated by Django 5.2.7 on 2025-10-22 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome_usuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField()),
                ('desc_evento', models.CharField(max_length=100)),
                ('desc_area', models.CharField(max_length=100)),
                ('desc_leitor', models.CharField(max_length=100)),
                ('ent_sai', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.usuario', to_field='matricula')),
            ],
        ),
    ]
