# Generated by Django 5.2.7 on 2025-10-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoriaUsuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
